# Generated by Django 2.2.3 on 2019-07-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientes', models.TextField(blank=True, null=True)),
                ('porcion', models.TextField(blank=True, null=True)),
                ('produccion', models.TextField(blank=True, null=True)),
                ('precios', models.TextField(blank=True, null=True)),
                ('costo_total', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
