# Generated by Django 2.2.3 on 2019-07-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='cantidad_insumo',
            field=models.FloatField(),
        ),
    ]
