# Generated by Django 2.2.3 on 2019-07-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendientes', '0002_receta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='porciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
