# Generated by Django 2.2.3 on 2019-07-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendientes', '0003_auto_20190722_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='preparacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='porciones',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
